site_name: Cobblemon Trainer Battle
nav:
  - Home: index.md
  - Configuration: configuration.md
  - Commands: commands.md
  - NPC Trainers: npctrainers.md
  - Items: items.md
  - Data Pack: datapack.md
  - Resource Pack: resourcepack.md
  - Trainer Team: trainerteam.md
theme: readthedocs
remote_name: github