site_name: Cobblemon Trainer Battle
nav:
  - Home: index.md
  - FAQ: faq.md
  - Deprecated: deprecated.md
  - Commands: commands.md
  - NPC Trainers: npctrainers.md
  - Villagers: villagers.md
  - Items: items.md
  - Rental Battle: rentalbattle.md
  - Data Pack: datapack.md
  - Resource Pack: resourcepack.md
  - Trainer Preset: trainerpreset.md
  - Trainer Team: trainerteam.md
theme: readthedocs
remote_name: github